"""P3.2 paystubs income table

The income source for deterministic precompute (P3.2). Mirrors the wide CSV
``scripts/extract_paystubs.py`` emits (SUMMARY block + itemized 401(k)). Money
columns are ``NUMERIC(14,2)`` (Appendix A); idempotent re-import upserts on the
unique ``dedupe_key`` (DA-19). The ``backend-ts`` ``PaystubEntity`` mirrors this
table (``synchronize:false``); the ``contracts/`` schema-parity check (DA-8)
keeps them identical.

Revision ID: ba4cb087cce7
Revises: f0bda61fcf45
Create Date: 2026-05-24 17:29:45.039703

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ba4cb087cce7"
down_revision: Union[str, Sequence[str], None] = "f0bda61fcf45"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "paystubs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("employer", sa.Text(), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("pay_date", sa.Date(), nullable=False),
        sa.Column("dedupe_key", sa.Text(), nullable=False),
        sa.Column("gross_pay", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("net_pay", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("taxes", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("deductions", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column(
            "reimbursements", sa.Numeric(precision=14, scale=2), server_default="0", nullable=False
        ),
        sa.Column(
            "retirement_401k_employee",
            sa.Numeric(precision=14, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "retirement_401k_employer",
            sa.Numeric(precision=14, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dedupe_key", name="uq_paystubs_dedupe_key"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("paystubs")
    # ### end Alembic commands ###
